<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeVirtualize.CSharp\CodeVirtualize.CSharp.csproj" />
    <ProjectReference Include="..\..\src\CodeVirtualize.Core\CodeVirtualize.Core.csproj" />
  </ItemGroup>
</Project>


